apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.1.1
      chart: ingress-nginx
      helm:
        version: v3
        parameters:
          - name: controller.replicaCount
            value: '1'
          - name: controller.service.type
            value: NodePort
        valueFiles:
          - $values/manifests/internal-nginx-values.yaml
    - repoURL: https://github.com/coveraver/argodeploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
