apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-base-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-project
  source:
    repoURL: https://github.com/coveraver/argodeploy.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
